# Generated by Django 5.0.2 on 2024-02-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=12, verbose_name='Place')),
                ('time', models.TimeField(verbose_name='Time')),
                ('habit_name', models.CharField(max_length=24, verbose_name='Habit')),
                ('activity', models.CharField(max_length=512, verbose_name='Activity')),
                ('enjoyable', models.BooleanField(default=False, verbose_name='Enjoyable')),
                ('reward', models.CharField(max_length=512, verbose_name='Reward')),
                ('periodicity', models.PositiveSmallIntegerField(verbose_name='Periodicity')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Time to complete')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_habits', to='tracker.habit', verbose_name='Linked Habit')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
