# Generated by Django 5.0.2 on 2024-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_habit_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='initial_date',
            field=models.DateField(default='2024-02-20', verbose_name='Initial date'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
